apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  workspaces:
    - name: source

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: source

    - name: git-clone
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: https://github.com/Vishnu12222344/ci-cd-final-project
        - name: revision
          value: main
        - name: deleteExisting
          value: "true"
        - name: subdirectory
          value: ""   # THIS FIXES THE DOCKERFILE ISSUE

    - name: flake8
      runAfter: [git-clone]
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: source

    - name: nose
      runAfter: [flake8]
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: source

    - name: buildah
      runAfter: [nose]
      taskRef:
        kind: ClusterTask
        name: buildah
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/sn-labs-pvishnu12222/flask-app
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
      workspaces:
        - name: source
          workspace: source
